DataSettings:
    data_dir: 'data_segmentation'
    output_dir: 'output'
    split_ratio: 0.80
    background_id: 0
    background_color: [255, 0, 0]
    classes: ['kit', 'membrane']
    class_ids: [1, 2]
    class_colors: [[0, 0, 255], [0, 255, 0]]
    resize_height: 800
TransformationParameters:
    rotate_limit: 80
    rotate_p: 0.8
    horizontal_flip_p: 0.5
    blur_limit: 5
    blur_p: 0.8
    color_jitter_brightness: 0.1
    color_jitter_contrast: 0.1
    color_jitter_saturation: 0.1
    color_jitter_p: 0.5
TrainingParameters:
    save_path: 'saved_models'
    train_validation_ratio: 0.8
    num_workers: 0
    batch_size: 4
    seed: 42
    num_epochs: 10
    num_classes: 3
    hidden_size: 256
    learning_rate: 5e-5
    score_thresholds: [0.85, 0.85]
    mask_thresholds: [0.85, 0.85]


